let problem1 (_data : string) : int =
    failwith "todo"

let problem2 (_data : string) : int =
    failwith "todo"
